# Created with package:mono_repo v3.0.1-dev
language: dart

jobs:
  include:
    - stage: smoke_test
      name: "SDK: dev; PKGS: mono_repo, test_pkg; TASKS: [`dartfmt -n --set-exit-if-changed .`, `dartanalyzer --fatal-infos --fatal-warnings .`]"
      dart: dev
      os: linux
      env: PKGS="mono_repo test_pkg"
      script: tool/ci.sh dartfmt dartanalyzer_0
    - stage: smoke_test
      name: "SDK: dev; PKG: mono_repo; TASKS: `cd ../ && dart mono_repo/bin/mono_repo.dart travis --validate`"
      dart: dev
      os: linux
      env: PKGS="mono_repo"
      script: tool/ci.sh command
    - stage: smoke_test
      name: "SDK: 2.7.0; PKG: mono_repo; TASKS: `dartanalyzer --fatal-warnings .`"
      dart: "2.7.0"
      os: linux
      env: PKGS="mono_repo"
      script: tool/ci.sh dartanalyzer_1
    - stage: unit_test
      name: "SDK: 2.7.0; PKG: mono_repo; TASKS: `pub run test -P presubmit --test-randomize-ordering-seed=random`"
      dart: "2.7.0"
      os: linux
      env: PKGS="mono_repo"
      script: tool/ci.sh test_0
    - stage: unit_test
      name: "SDK: 2.7.0; PKG: mono_repo; TASKS: `pub run test -P presubmit --test-randomize-ordering-seed=random`"
      dart: "2.7.0"
      os: windows
      env: PKGS="mono_repo"
      script: tool/ci.sh test_0
    - stage: unit_test
      name: "SDK: dev; PKG: mono_repo; TASKS: `pub run test -P presubmit --test-randomize-ordering-seed=random`"
      dart: dev
      os: linux
      env: PKGS="mono_repo"
      script: tool/ci.sh test_0
    - stage: unit_test
      name: "SDK: dev; PKG: mono_repo; TASKS: `pub run test -P presubmit --test-randomize-ordering-seed=random`"
      dart: dev
      os: windows
      env: PKGS="mono_repo"
      script: tool/ci.sh test_0
    - stage: unit_test
      name: "SDK: dev; PKG: test_pkg; TASKS: `pub run test --test-randomize-ordering-seed=random`"
      dart: dev
      os: linux
      env: PKGS="test_pkg"
      script: tool/ci.sh test_1

stages:
  - smoke_test
  - unit_test

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.pub-cache"
    - mono_repo/.dart_tool/build
