# Created with https://github.com/dart-lang/mono_repo
language: dart

jobs:
  include:
    - stage: smoke_test
      script: ./tool/travis.sh dartfmt dartanalyzer
      env: PKG="mono_repo"
      dart: dev
    - stage: build
      script: ./tool/travis.sh command_0
      env: PKG="mono_repo"
      dart: dev
    - stage: unit_test
      script: ./tool/travis.sh command_1 command_2
      env: PKG="mono_repo"
      dart: dev

stages:
  - smoke_test
  - build
  - unit_test

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
    - mono_repo/.dart_tool/build
