name: pubspek
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Kevin Moore <email@example.com>

environment:
  sdk: '>=2.0.0-dev.54 <2.0.0'

dependencies:
  json_annotation: ^0.2.6
  pub_semver: ^1.3.2
  yaml: ^2.1.12

dev_dependencies:
  build_runner: ^0.8.0
  json_serializable: ^0.5.5
  test: ^0.12.0
