name: mono_repo
description: >-
  CLI tools to make it easier to manage a single source repository containing
  multiple Dart packages.
version: 4.2.0-dev
repository: https://github.com/google/mono_repo.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  checked_yaml: ^2.0.0
  collection: ^1.14.3
  graphs: ^2.0.0
  io: ^1.0.0
  json_annotation: ^4.0.0
  meta: ^1.0.0
  path: ^1.4.1
  pub_semver: ^2.0.0
  pubspec_parse: ^1.0.0
  yaml: ^3.0.0
  yaml_edit: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.1
  build_test: ^2.0.0
  build_verify: ^2.0.0
  build_version: ^2.0.0
  json_serializable: ^4.0.0
  # Because we use the ignore_for_file build.yaml option
  source_gen: ^1.0.0
  term_glyph: ^1.0.0
  test: ^1.16.5
  test_descriptor: ^2.0.0
  test_process: ^2.0.0

executables:
  mono_repo:
