name: mono_repo
description: Manage repositories with multiple Dart packages
version: 0.3.3-dev
homepage: https://github.com/dart-lang/mono_repo
author: Dart Team <misc@dartlang.org>

environment:
  sdk: '>=2.0.0-dev.54 <2.0.0'

dependencies:
  args: ^1.4.0
  collection: ^1.14.3
  graphs: ^0.1.0
  io: ^0.3.2+1
  json_annotation: ^0.2.7
  path: ^1.4.1
  pub_semver: ^1.3.2
  pubspec_parse: ^0.1.0
  yaml: ^2.1.12

dev_dependencies:
  build_runner: ^0.8.0
  json_serializable: ^0.5.6
  test: ^0.12.0
  test_descriptor: ^1.0.0
  test_process: ^1.0.1

executables:
  mono_repo:
