name: mono_repo
description: Manage repositories with multiple Dart packages
version: 0.2.2-dev
homepage: https://github.com/dart-lang/mono_repo
author: Dart Team <misc@dartlang.org>

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  args: ">=0.13.7 <2.0.0"
  collection: ^1.14.3
  io: ^0.3.2
  json_annotation: ^0.2.2
  path: ^1.4.1
  pub_semver: ^1.3.2
  yaml: ^2.1.12

dev_dependencies:
  build_runner: ^0.7.0
  json_serializable: ^0.3.0
  test: ^0.12.0
  test_descriptor: ^1.0.0
  test_process: ^1.0.1

executables:
  mono_repo:
