name: mono_repo
description: >-
  CLI tools to make it easier to manage a single source repository containing
  multiple Dart packages.
version: 2.3.1-dev
homepage: https://github.com/dart-lang/mono_repo

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  args: ^1.4.0
  checked_yaml: ^1.0.0
  collection: ^1.14.3
  graphs: ^0.2.0
  io: ^0.3.2+1
  json_annotation: ^3.0.0
  meta: ^1.0.0
  path: ^1.4.1
  pub_semver: ^1.3.2
  pubspec_parse: ^0.1.0
  yaml: ^2.1.12

dev_dependencies:
  build_runner: ^1.0.0
  build_test: '>=0.10.0 <2.0.0'
  build_verify: ^1.0.0
  build_version: ^2.0.0
  build_vm_compilers: '>=0.1.0 <2.0.0'
  json_serializable: ^3.2.0
  # Because we use the ignore_for_file build.yaml option
  source_gen: ^0.9.5
  term_glyph: ^1.0.0
  test: ^1.3.0
  test_descriptor: ^1.0.0
  test_process: ^1.0.1

executables:
  mono_repo:
